#@description flreconstruct configuration script from CD input
#@key_label  "name"
#@meta_label "type"

###########################################
# FLRECONSTRUCT PLUGINS
###########################################
[name="flreconstruct" type="flreconstruct::section"]
experimentalSetupURN : string = "urn:snemo:demonstrator:setup:3.0"


[name="flreconstruct.plugins" type="flreconstruct::section"]
plugins : string[1] ="SNCuts" 

SNCuts.directory : string = "/sps/nemo/scratch/apitolaj/Modules/SNCuts/build"
###########################################
# PIPELINE
###########################################

[name="pipeline" type="dpp::chain_module"]
modules : string[1] = "SNCuts" 

###########################################
# SNCuts                   
###########################################

[name="SNCuts" type="SNCuts"]

source_pos_path : string = "/sps/nemo/scratch/apitolaj/template_scripts/testScripts/configuration/source_positions_NEW.txt"

useEventHasVertexCloseToCalibSource : boolean = true
	
#number of kinked tracks cut
hasNumberofKinks : string = "1 0"
	
#1 track has 1 associated calo hit
useEventTrackHasOneAssocCaloHit : boolean = true
		
minSumEnergy : real = 0.0
maxSumEnergy : real = 3500.0
		
#parameters of elips for close to calib source vertex position cut
source_cut_ellipse_Y: real = 15.0 mm
source_cut_ellipse_Z: real = 40.0 mm 
        
#end



