#@description Simulation tutorial
#@key_label "name"
#@meta_label "type"

[name="flsimulate" type="flsimulate::section"]
numberOfEvents : integer = 1000

[name="flsimulate.variantService" type="flsimulate::section"]
profile : string as path = "/sps/nemo/scratch/apitolaj/template_scripts/testScripts/configuration/profiles/simu_source_0_5.profile"
