#@description Simulation tutorial
#@key_label "name"
#@meta_label "type"

[name="flsimulate" type="flsimulate::section"]
numberOfEvents : integer = 100

[name="flsimulate.variantService" type="flsimulate::section"]
profile : string as path = "/sps/nemo/scratch/apitolaj/new_template/configuration/simu_orig.profile"
