# - Configuration

#@description Simple pipeline using the TestModulePipeline
#@key_label "name"
#@meta_label "type"

# - Module load section
[name="flreconstruct.plugins" type="flreconstruct::section"]
	plugins : string[1] = "MiModule"
	MiModule.directory : string = "/sps/nemo/scratch/apitolaj/Modules/MiModule/lib"

[name="pipeline" type="MiModule"]



